// Generated by scripts/fetch_enriched_catalog.py
import 'models/catalog_plant.dart';

const plantsCatalog = <CatalogPlant>[
  CatalogPlant(
    id: 90001,
    commonName: 'Plante à feuillage',
    wateringDays: 7,
    isGeneric: true,
  ),
  CatalogPlant(
    id: 90002,
    commonName: 'Succulente / Cactus',
    wateringDays: 17,
    isGeneric: true,
  ),
  CatalogPlant(
    id: 90003,
    commonName: 'Plante à fleurs',
    wateringDays: 5,
    isGeneric: true,
  ),
];

CatalogPlant? catalogPlantById(int id) {
  for (final plant in plantsCatalog) {
    if (plant.id == id) return plant;
  }
  return null;
}

List<CatalogPlant> searchPlants(String query) {
  final normalized = query.trim().toLowerCase();
  if (normalized.isEmpty) {
    return plantsCatalog.where((plant) => !plant.isGeneric).toList();
  }

  final matches = plantsCatalog
      .where((plant) => plant.commonName.toLowerCase().contains(normalized))
      .toList();

  if (matches.isNotEmpty) return matches;

  return plantsCatalog.where((plant) => plant.isGeneric).toList();
}
