// Generated by scripts/fetch_perenual_photos.py — do not edit by hand.
import 'models/catalog_plant.dart';

const plantsCatalog = <CatalogPlant>[
  CatalogPlant(
    id: 1,
    commonName: 'flowering-maple',
    wateringDays: 8,
    imageAsset: 'assets/plants/images/flowering_maple_425.jpg',
  ),
  CatalogPlant(
    id: 2,
    commonName: 'Jacob\'s coat',
    wateringDays: 4,
    imageAsset: 'assets/plants/images/jacobs_coat_434.jpg',
  ),
  CatalogPlant(
    id: 3,
    commonName: 'desert rose',
    wateringDays: 8,
    imageAsset: 'assets/plants/images/desert_rose_540.jpg',
  ),
  CatalogPlant(
    id: 4,
    commonName: 'maidenhair fern',
    wateringDays: 2,
    imageAsset: 'assets/plants/images/maidenhair_fern_543.jpg',
  ),
  CatalogPlant(
    id: 5,
    commonName: 'delta maidenhair fern',
    wateringDays: 2,
    imageAsset: 'assets/plants/images/delta_maidenhair_fern_546.jpg',
  ),
  CatalogPlant(
    id: 6,
    commonName: 'urn plant',
    wateringDays: 2,
    imageAsset: 'assets/plants/images/urn_plant_549.jpg',
  ),
  CatalogPlant(
    id: 7,
    commonName: 'stalked aeonium',
    wateringDays: 8,
    imageAsset: 'assets/plants/images/stalked_aeonium_551.jpg',
  ),
  CatalogPlant(
    id: 8,
    commonName: 'lipstick plant',
    wateringDays: 8,
    imageAsset: 'assets/plants/images/lipstick_plant_552.jpg',
  ),
  CatalogPlant(
    id: 9,
    commonName: 'Philippine evergreen',
    wateringDays: 8,
    imageAsset: 'assets/plants/images/philippine_evergreen_625.jpg',
  ),
  CatalogPlant(
    id: 10,
    commonName: 'Chinese evegreen',
    wateringDays: 8,
    imageAsset: 'assets/plants/images/chinese_evegreen_626.jpg',
  ),
  CatalogPlant(
    id: 9001,
    commonName: 'Plante à feuillage',
    wateringDays: 7,
    isGeneric: true,
  ),
  CatalogPlant(
    id: 9002,
    commonName: 'Succulente / Cactus',
    wateringDays: 17,
    isGeneric: true,
  ),
  CatalogPlant(
    id: 9003,
    commonName: 'Plante à fleurs',
    wateringDays: 5,
    isGeneric: true,
  ),
];

CatalogPlant? catalogPlantById(int id) {
  for (final plant in plantsCatalog) {
    if (plant.id == id) return plant;
  }
  return null;
}

List<CatalogPlant> searchPlants(String query) {
  final normalized = query.trim().toLowerCase();
  if (normalized.isEmpty) {
    return plantsCatalog.where((plant) => !plant.isGeneric).toList();
  }

  final matches = plantsCatalog
      .where((plant) => plant.commonName.toLowerCase().contains(normalized))
      .toList();

  if (matches.isNotEmpty) return matches;

  return plantsCatalog.where((plant) => plant.isGeneric).toList();
}
